incident_titles = [
    {"title": "🔥 Fire Drill: Disk space at 95%", "urgency": "high"},
    {"title": "🔥 Fire Drill: CPU spike on backend pod", "urgency": "high"},
    {"title": "🔥 Fire Drill: High error rate on API gateway", "urgency": "high"},
    {"title": "🔥 Fire Drill: Database connection pool exhausted", "urgency": "high"},
    {"title": "🔥 Fire Drill: Memory leak detected in service", "urgency": "high"},
    {"title": "🔥 Fire Drill: Network latency spike", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service dependency timeout", "urgency": "high"},
    {"title": "🔥 Fire Drill: Unusual traffic pattern detected", "urgency": "low"},
    {"title": "🔥 Fire Drill: Authentication failures spiking", "urgency": "high"},
    {"title": "🔥 Fire Drill: Message queue backlog growing", "urgency": "low"},
    {"title": "🔥 Fire Drill: 3rd party API outage", "urgency": "high"},
    {"title": "🔥 Fire Drill: Configuration drift detected", "urgency": "low"},
    {"title": "🔥 Fire Drill: SSL certificate expiring soon", "urgency": "low"},
    {"title": "🔥 Fire Drill: Sudden drop in successful logins", "urgency": "high"},
    {"title": "🔥 Fire Drill: Data replication lag", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service restart loop detected", "urgency": "high"},
    {"title": "🔥 Fire Drill: Elevated 5xx errors", "urgency": "high"},
    {"title": "🔥 Fire Drill: API rate limit exceeded", "urgency": "low"},
    {"title": "🔥 Fire Drill: Backup job failed", "urgency": "low"},
    {"title": "🔥 Fire Drill: Host unreachable", "urgency": "high"},
    {"title": "🔥 Fire Drill: DNS resolution failure", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service health check failed", "urgency": "high"},
    {"title": "🔥 Fire Drill: Unexpected service shutdown", "urgency": "high"},
    {"title": "🔥 Fire Drill: Elevated latency in EU region", "urgency": "low"},
    {"title": "🔥 Fire Drill: Payment gateway timeout", "urgency": "high"},
    {"title": "🔥 Fire Drill: S3 bucket access denied", "urgency": "high"},
    {"title": "🔥 Fire Drill: Redis cache miss spike", "urgency": "low"},
    {"title": "🔥 Fire Drill: Kafka consumer lag", "urgency": "low"},
    {"title": "🔥 Fire Drill: Webhook delivery failures", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service deployment failed", "urgency": "high"},
    {"title": "🔥 Fire Drill: Outbound email delivery delay", "urgency": "low"},
    {"title": "🔥 Fire Drill: Inbound SMS not received", "urgency": "low"},
    {"title": "🔥 Fire Drill: Elevated error rate in mobile app", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service not scaling as expected", "urgency": "low"},
    {"title": "🔥 Fire Drill: Cloud provider API error", "urgency": "high"},
    {"title": "🔥 Fire Drill: Certificate revocation warning", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service quota exceeded", "urgency": "high"},
    {"title": "🔥 Fire Drill: Unusual login location detected", "urgency": "low"},
    {"title": "🔥 Fire Drill: Elevated CPU steal time", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service dependency degraded", "urgency": "high"},
    {"title": "🔥 Fire Drill: Out-of-memory kill event", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service stuck in terminating state", "urgency": "high"},
    {"title": "🔥 Fire Drill: Elevated disk IO wait", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 404", "urgency": "low"},
    {"title": "🔥 Fire Drill: Elevated error rate in US region", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service not responding to pings", "urgency": "high"},
    {"title": "🔥 Fire Drill: Elevated error rate in APAC region", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service deployment rollback", "urgency": "high"},
    {"title": "🔥 Fire Drill: Elevated error rate in EU region", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 500", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 403", "urgency": "low"},
    {"title": "🔥 Fire Drill: Elevated error rate in staging", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 401", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 502", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 503", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 504", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 400", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 422", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 429", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 301", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 302", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 307", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 308", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 418", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 451", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 520", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 521", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 522", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 523", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 524", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 525", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 526", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 527", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 530", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 599", "urgency": "high"},
    {"title": "🔥 Fire Drill: Service endpoint returning 999", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 600", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 601", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 602", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 603", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 604", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 605", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 606", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 607", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 608", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 609", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 610", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 611", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 612", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 613", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 614", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 615", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 616", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 617", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 618", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 619", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 620", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 621", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 622", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 623", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 624", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 625", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 626", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 627", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 628", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 629", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 630", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 631", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 632", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 633", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 634", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 635", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 636", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 637", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 638", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 639", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 640", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 641", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 642", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 643", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 644", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 645", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 646", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 647", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 648", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 649", "urgency": "low"},
    {"title": "🔥 Fire Drill: Service endpoint returning 650", "urgency": "low"},
] 